name: Run Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./MotorcycleRent.sln
      
    - name: Build
      run: dotnet build ./MotorcycleRent.sln --no-restore
      
    - name: Run tests
      run: dotnet test ./MotorcycleRent.sln --no-build --verbosity normal
      
    - name: Generate coverage report
      run: |
        dotnet test ./MotorcycleRent.sln --collect:"Code Coverage" --results-directory:"TestResults"
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: TestResults